apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklog-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: worklog-backend
  template:
    metadata:
      labels:
        app: worklog-backend
    spec:
      containers:
      - image: docker.io/divakar51/worklog-backend:latest
        name: worklog-backend
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---

apiVersion: v1
kind: Service
metadata:
  name: worklog-backend
spec:
  type: NodePort
  selector:
    app: worklog-backend
  ports:
  - port: 5000